# Generated by Django 4.2.4 on 2023-08-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_calendar_note_note_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='times',
            field=models.DateTimeField(),
        ),
    ]
